services:
  # old style
  turted_push:
      class: Turted\TurtedBundle\Service\TurtedRestPushService
      arguments:
        - '%turted%'
        - '@logger'

  # new style for autowiring
  Turted\TurtedBundle\Service\TurtedRestPushService: '@turted_push'
